<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="0" total="6" passed="4" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-09-03T11:55:03 IST" name="Suite" finished-at="2025-09-03T11:55:19 IST" duration-ms="15375">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationsTest.LoginErrorValidation()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" name="LoginErrorValidation" class="SeleniumFramework.Tests.ErrorValidationsTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purchase">
        <method signature="StandAloneTest2.submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" name="submitOrder" class="SeleniumFramework.Tests.StandAloneTest2"/>
      </group> <!-- Purchase -->
    </groups>
    <test started-at="2025-09-03T11:55:03 IST" name="Error validation test" finished-at="2025-09-03T11:55:19 IST" duration-ms="15375">
      <class name="SeleniumFramework.Tests.ErrorValidationsTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:03 IST" name="launchApplication" finished-at="2025-09-03T11:55:07 IST" duration-ms="3384" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="LoginErrorValidation()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:07 IST" name="LoginErrorValidation" finished-at="2025-09-03T11:55:08 IST" duration-ms="991" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumFramework.Tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:08 IST" name="tearDown" finished-at="2025-09-03T11:55:08 IST" duration-ms="82" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:08 IST" name="launchApplication" finished-at="2025-09-03T11:55:10 IST" duration-ms="2457" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="LoginErrorValidation()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:10 IST" name="LoginErrorValidation" finished-at="2025-09-03T11:55:12 IST" duration-ms="1150" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email  password.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at SeleniumFramework.Tests.ErrorValidationsTest.LoginErrorValidation(ErrorValidationsTest.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:463)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- LoginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:12 IST" name="tearDown" finished-at="2025-09-03T11:55:12 IST" duration-ms="89" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:12 IST" name="launchApplication" finished-at="2025-09-03T11:55:15 IST" duration-ms="3109" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="ProductErrorValdiation()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:15 IST" name="ProductErrorValdiation" finished-at="2025-09-03T11:55:19 IST" duration-ms="3519" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- ProductErrorValdiation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.ErrorValidationsTest@239105a8]" started-at="2025-09-03T11:55:19 IST" name="tearDown" finished-at="2025-09-03T11:55:19 IST" duration-ms="202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumFramework.Tests.ErrorValidationsTest -->
    </test> <!-- Error validation test -->
    <test started-at="2025-09-03T11:55:03 IST" name="Submit  order" finished-at="2025-09-03T11:55:18 IST" duration-ms="15037">
      <class name="SeleniumFramework.Tests.StandAloneTest2">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:03 IST" name="launchApplication" finished-at="2025-09-03T11:55:06 IST" duration-ms="2202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:06 IST" name="submitOrder" data-provider="getData" finished-at="2025-09-03T11:55:10 IST" duration-ms="4258" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Anjali@gmail.com1, product=ADIDAS ORIGINAL, email=Anjali@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:10 IST" name="tearDown" finished-at="2025-09-03T11:55:10 IST" duration-ms="86" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:10 IST" name="launchApplication" finished-at="2025-09-03T11:55:12 IST" duration-ms="1527" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="submitOrder(java.util.HashMap)[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:12 IST" name="submitOrder" data-provider="getData" finished-at="2025-09-03T11:55:16 IST" duration-ms="4546" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=Anjali@123, product=ZARA COAT 3, email=Anjali1111@gmail.com}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- submitOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:16 IST" name="tearDown" finished-at="2025-09-03T11:55:16 IST" duration-ms="112" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:16 IST" name="launchApplication" finished-at="2025-09-03T11:55:18 IST" duration-ms="1523" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="checkHistoryOrder()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:18 IST" name="checkHistoryOrder" finished-at="2025-09-03T11:55:18 IST" depends-on-methods="SeleniumFramework.Tests.StandAloneTest2.submitOrder" duration-ms="599" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkHistoryOrder -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:SeleniumFramework.Tests.StandAloneTest2@5167f57d]" started-at="2025-09-03T11:55:18 IST" name="tearDown" finished-at="2025-09-03T11:55:18 IST" duration-ms="130" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- SeleniumFramework.Tests.StandAloneTest2 -->
    </test> <!-- Submit  order -->
  </suite> <!-- Suite -->
</testng-results>
